# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import server_pb2 as server__pb2


class ServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.find_successor = channel.unary_unary(
        '/server.Server/find_successor',
        request_serializer=server__pb2.FindSucRequest.SerializeToString,
        response_deserializer=server__pb2.FindSucResponse.FromString,
        )
    self.live_predecessor = channel.unary_unary(
        '/server.Server/live_predecessor',
        request_serializer=server__pb2.PredecessorRequest.SerializeToString,
        response_deserializer=server__pb2.PredecessorResponse.FromString,
        )
    self.find_succlist = channel.unary_unary(
        '/server.Server/find_succlist',
        request_serializer=server__pb2.FindSucclistRequest.SerializeToString,
        response_deserializer=server__pb2.FindSucclistResponse.FromString,
        )
    self.find_predecessor = channel.unary_unary(
        '/server.Server/find_predecessor',
        request_serializer=server__pb2.EmptyRequest.SerializeToString,
        response_deserializer=server__pb2.FindPredResponse.FromString,
        )
    self.rectify = channel.unary_unary(
        '/server.Server/rectify',
        request_serializer=server__pb2.RectifyRequest.SerializeToString,
        response_deserializer=server__pb2.RectifyResponse.FromString,
        )
    self.get_node_status = channel.unary_unary(
        '/server.Server/get_node_status',
        request_serializer=server__pb2.EmptyRequest.SerializeToString,
        response_deserializer=server__pb2.NodeStatus.FromString,
        )
    self.replicate_entries = channel.unary_unary(
        '/server.Server/replicate_entries',
        request_serializer=server__pb2.ReplicateRequest.SerializeToString,
        response_deserializer=server__pb2.ReplicateResponse.FromString,
        )
    self.get = channel.unary_unary(
        '/server.Server/get',
        request_serializer=server__pb2.GetRequest.SerializeToString,
        response_deserializer=server__pb2.GetResponse.FromString,
        )
    self.put = channel.unary_unary(
        '/server.Server/put',
        request_serializer=server__pb2.PutRequest.SerializeToString,
        response_deserializer=server__pb2.PutResponse.FromString,
        )


class ServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def find_successor(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def live_predecessor(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def find_succlist(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def find_predecessor(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def rectify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_node_status(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def replicate_entries(self, request, context):
    """defined by ourselves
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def put(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'find_successor': grpc.unary_unary_rpc_method_handler(
          servicer.find_successor,
          request_deserializer=server__pb2.FindSucRequest.FromString,
          response_serializer=server__pb2.FindSucResponse.SerializeToString,
      ),
      'live_predecessor': grpc.unary_unary_rpc_method_handler(
          servicer.live_predecessor,
          request_deserializer=server__pb2.PredecessorRequest.FromString,
          response_serializer=server__pb2.PredecessorResponse.SerializeToString,
      ),
      'find_succlist': grpc.unary_unary_rpc_method_handler(
          servicer.find_succlist,
          request_deserializer=server__pb2.FindSucclistRequest.FromString,
          response_serializer=server__pb2.FindSucclistResponse.SerializeToString,
      ),
      'find_predecessor': grpc.unary_unary_rpc_method_handler(
          servicer.find_predecessor,
          request_deserializer=server__pb2.EmptyRequest.FromString,
          response_serializer=server__pb2.FindPredResponse.SerializeToString,
      ),
      'rectify': grpc.unary_unary_rpc_method_handler(
          servicer.rectify,
          request_deserializer=server__pb2.RectifyRequest.FromString,
          response_serializer=server__pb2.RectifyResponse.SerializeToString,
      ),
      'get_node_status': grpc.unary_unary_rpc_method_handler(
          servicer.get_node_status,
          request_deserializer=server__pb2.EmptyRequest.FromString,
          response_serializer=server__pb2.NodeStatus.SerializeToString,
      ),
      'replicate_entries': grpc.unary_unary_rpc_method_handler(
          servicer.replicate_entries,
          request_deserializer=server__pb2.ReplicateRequest.FromString,
          response_serializer=server__pb2.ReplicateResponse.SerializeToString,
      ),
      'get': grpc.unary_unary_rpc_method_handler(
          servicer.get,
          request_deserializer=server__pb2.GetRequest.FromString,
          response_serializer=server__pb2.GetResponse.SerializeToString,
      ),
      'put': grpc.unary_unary_rpc_method_handler(
          servicer.put,
          request_deserializer=server__pb2.PutRequest.FromString,
          response_serializer=server__pb2.PutResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'server.Server', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
